name: SyncBoard CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install and Test Backend
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: supersecretkey
        run: |
          cd server
          npm install
          npm test

      - name: Install and Test Frontend
        run: |
          cd client
          npm install
          npm test
